-- MySQL Script generated by MySQL Workbench
-- Thu May 21 22:49:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vsdb` DEFAULT CHARACTER SET utf8 ;
USE `vsdb` ;

-- -----------------------------------------------------
-- Table `vsdb`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vsdb`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vsdb`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vsdb`.`model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vsdb`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vsdb`.`brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vsdb`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vsdb`.`vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `provider_id` INT NOT NULL,
  `pricing` DECIMAL(5,2) NOT NULL,
  `type_id` INT NOT NULL,
  `model_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicle_type_idx` (`type_id` ASC) VISIBLE,
  INDEX `fk_vehicle_model1_idx` (`model_id` ASC) VISIBLE,
  INDEX `fk_vehicle_brand1_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `fk_vehicle_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `vsdb`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_model1`
    FOREIGN KEY (`model_id`)
    REFERENCES `vsdb`.`model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `vsdb`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
