-- MySQL Script generated by MySQL Workbench
-- Sat May 23 17:53:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pdb` DEFAULT CHARACTER SET utf8 ;
USE `pdb` ;

-- -----------------------------------------------------
-- Table `pdb`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdb`.`payment_method` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdb`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdb`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reservation_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `payment_method_id` INT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `reservation_id_UNIQUE` (`reservation_id` ASC) VISIBLE,
  INDEX `fk_payment_payment_method_idx` (`payment_method_id` ASC) VISIBLE,
  INDEX `fk_payment_status1_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_payment_payment_method`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `pdb`.`payment_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_status1`
    FOREIGN KEY (`status`)
    REFERENCES `pdb`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
