CREATE SCHEMA IF NOT EXISTS pmdb;
SET SCHEMA pmdb;

CREATE TABLE IF NOT EXISTS provider (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  company VARCHAR(128),
  email VARCHAR(128) NOT NULL,
  phone VARCHAR(10) NOT NULL,
  location VARCHAR(128) NOT NULL,
  currency VARCHAR(4) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS email_UNIQUE ON provider(email);
CREATE UNIQUE INDEX IF NOT EXISTS phone_UNIQUE ON provider(phone);
