-- MySQL Script generated by MySQL Workbench
-- Fri May 15 22:07:01 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pmdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pmdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pmdb` DEFAULT CHARACTER SET utf8 ;
USE `pmdb` ;

-- -----------------------------------------------------
-- Table `pmdb`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmdb`.`provider` (
  `provider_id` INT NOT NULL AUTO_INCREMENT,
  `company` VARCHAR(128) NULL,
  `email` VARCHAR(128) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `location` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`provider_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
