spring.application.name=pmmicro
server.servlet.context-path=/api/v1
springdoc.api-docs.path=/docs

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Se recomienda utilizar las variables de entorno, pero también es posible definir,
# las credenciales y URL desde este archivo,
#

# spring.datasource.url=jdbc:mariadb://server-domain:3306/pmdb?useSSL=false&serverTimezone=UTC
# spring.datasource.username=myuser
# spring.datasource.password=mypass
