x-db-common: &db-common
  environment: &db-common-env
    MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    MARIADB_USER: ${DB_USER}
    MARIADB_PASSWORD: ${DB_PASSWORD}

  image: mariadb:12.3.1-ubi10-rc
  restart: always
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
    interval: 20s
    timeout: 20s
    retries: 2
    start_period: 10s


x-micro-common: &micro-common
    environment: &micro-common-env
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      LOGGING_LEVEL_ES_UPM_CDELAOF26: "${LOGGING_LVL:-INFO}"

    build: &micro-common-build
      dockerfile: ../backend.Dockerfile
    restart: always


services:
  pmmicro:
    <<: *micro-common
    environment:
      <<: *micro-common-env
      SPRING_DATASOURCE_URL: jdbc:mariadb://pmmicro-db:3306/pmdb?useSSL=false&serverTimezone=UTC
      
    container_name: pmmicro
    build: 
      <<: *micro-common-build
      context: pmmicro
      args:
        ARTIFACT: pmmicro-0.0.2.jar
    ports:
      - 8080:8080
    depends_on:
      pmmicro-db:
        condition: service_healthy
    networks:
      - pmmicro-net
      - internal

  pmmicro-db:
    <<: *db-common
    environment: 
      <<: *db-common-env
      MARIADB_DATABASE: "pmdb"

    container_name: pmmicro-db
    volumes:
      - pmmicro-db-data:/var/lib/mysql
      - ./pmmicro/db:/docker-entrypoint-initdb.d
    networks:
      - pmmicro-net


  vimicro:
    <<: *micro-common
    environment:
      <<: *micro-common-env
      SPRING_DATASOURCE_URL: jdbc:mariadb://vimicro-db:3306/vidb?useSSL=false&serverTimezone=UTC
      
    container_name: vimicro
    build: 
      <<: *micro-common-build
      context: vimicro
      args:
        ARTIFACT: vimicro-v0.0.3.jar
    ports:
      - 8081:8080
    depends_on:
      vimicro-db:
        condition: service_healthy
    networks:
      - vimicro-net
      - internal

  vimicro-db:
    <<: *db-common
    environment:
      <<: *db-common-env
      MARIADB_DATABASE: "vidb"

    container_name: vimicro-db
    volumes:
      - vimicro-db-data:/var/lib/mysql
      - ./vimicro/db:/docker-entrypoint-initdb.d
    networks:
      - vimicro-net


  tmicro:
    <<: *micro-common
    container_name: tmicro
    build: 
      <<: *micro-common-build
      context: tmicro
      args:
        ARTIFACT: tmicro-0.0.1-1.jar
    ports:
      - 8082:8080
    networks:
      - tmicro-net
      - internal


  vsmicro:
    <<: *micro-common
    environment:
      <<: *micro-common-env
      SPRING_DATASOURCE_URL: jdbc:mariadb://vsmicro-db:3306/vsdb?useSSL=false&serverTimezone=UTC
      PMMICRO_BASE_URL: http://pmmicro:8080/api/v1
      VIMICRO_BASE_URL: http://vimicro:8080/api/v1
      TMICRO_BASE_URL: http://tmicro:8080/api/v1
      
    container_name: vsmicro
    build: 
      <<: *micro-common-build
      context: vsmicro
      args:
        ARTIFACT: vsmicro-0.0.1.jar
    ports:
      - 8083:8080
    depends_on:
      vsmicro-db:
        condition: service_healthy
      pmmicro:
        condition: service_started
      vimicro:
        condition: service_started
      tmicro:
        condition: service_started

    networks:
      - vsmicro-net
      - internal

  vsmicro-db:
    <<: *db-common
    environment:
      <<: *db-common-env
      MARIADB_DATABASE: "vsdb"

    container_name: vsmicro-db
    volumes:
      - vsmicro-db-data:/var/lib/mysql
      - ./vsmicro/db:/docker-entrypoint-initdb.d
    networks:
      - vsmicro-net


  pmicro:
    <<: *micro-common
    environment:
      <<: *micro-common-env
      SPRING_DATASOURCE_URL: jdbc:mariadb://pmicro-db:3306/pdb?useSSL=false&serverTimezone=UTC
      VIMICRO_BASE_URL: http://vimicro:8080/api/v1
      
    container_name: pmicro
    build: 
      <<: *micro-common-build
      context: pmicro
      args:
        ARTIFACT: pmicro-0.0.1.jar
    ports:
      - 8084:8080
    depends_on:
      pmicro-db:
        condition: service_healthy
      vimicro:
        condition: service_started
      
    networks:
      - pmicro-net
      - internal

  pmicro-db:
    <<: *db-common
    environment:
      <<: *db-common-env
      MARIADB_DATABASE: "pdb"

    container_name: pmicro-db
    volumes:
      - pmicro-db-data:/var/lib/mysql
      - ./pmicro/db:/docker-entrypoint-initdb.d
    networks:
      - pmicro-net

volumes:
  pmmicro-db-data: {}
  vimicro-db-data: {}
  vsmicro-db-data: {}
  pmicro-db-data: {}

networks:
  internal:
    driver: bridge

  pmmicro-net:
    driver: bridge

  vimicro-net:
    driver: bridge

  tmicro-net:
    driver: bridge

  vsmicro-net:
    driver: bridge

  pmicro-net:
    driver: bridge
