-- MySQL Script generated by MySQL Workbench
-- Mon May 18 20:04:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vidb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vidb` DEFAULT CHARACTER SET utf8 ;
USE `vidb` ;

-- -----------------------------------------------------
-- Table `vidb`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidb`.`inventory` (
  `id` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidb`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidb`.`vehicle` (
  `license_plate` VARCHAR(7) NOT NULL,
  `inventory_id` INT NOT NULL,
  `user_id` INT NULL,
  `in_use` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`license_plate`),
  INDEX `fk_vehicle_inventory_idx` (`inventory_id` ASC) VISIBLE,
  CONSTRAINT `fk_vehicle_inventory`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `vidb`.`inventory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vidb`.`rent_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vidb`.`rent_date` (
  `id` INT NOT NULL,
  `license_plate` VARCHAR(7) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_RentDates_vehicle1_idx` (`license_plate` ASC) VISIBLE,
  CONSTRAINT `fk_RentDates_vehicle1`
    FOREIGN KEY (`license_plate`)
    REFERENCES `vidb`.`vehicle` (`license_plate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `vidb`;

DELIMITER $$
USE `vidb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `vidb`.`inventory_increase` AFTER INSERT ON `vehicle` FOR EACH ROW
BEGIN
	IF NEW.in_use = 0 THEN
		UPDATE inventory
		SET amount = amount + 1
		WHERE id = NEW.inventory_id;
	  END IF;
END$$

USE `vidb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `vidb`.`inventory_adjustment` BEFORE UPDATE ON `vehicle` FOR EACH ROW
BEGIN
	IF OLD.in_use = 0 AND NEW.in_use = 1 THEN
		UPDATE inventory SET amount = amount - 1 WHERE id = NEW.inventory_id;
        IF (SELECT amount FROM inventory WHERE id = NEW.inventory_id) < 0 THEN
			-- This should never happen unless amount is modified externally
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Insufficient inventory for update';
		END IF;
	ELSEIF OLD.in_use = 1 AND NEW.in_use = 0 THEN
		UPDATE inventory SET amount = amount + 1 WHERE id = NEW.inventory_id;
	END IF;
END$$

USE `vidb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `vidb`.`inventory_adjustment_on_removal` BEFORE DELETE ON `vehicle` FOR EACH ROW
BEGIN
	IF OLD.in_use = 0 THEN
		UPDATE inventory
		SET amount = amount - 1
		WHERE id = OLD.inventory_id;
        IF (SELECT amount FROM inventory WHERE id = NEW.inventory_id) < 0 THEN
			-- This should never happen unless amount is modified externally
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Insufficient inventory for delete';
		END IF;
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
